const cityWeather = {
    city: "Berlin",
    country: "Germany",
    temperature: 20,
    feelsLike: 18,
    humidity: 46,
    wind: 14,
    precipitation: 0,
    daily: [
        { day: "Tue", icon: "🌧", max: 20, min: 14 },
        { day: "Wed", icon: "🌧", max: 21, min: 15 },
        { day: "Thu", icon: "☀", max: 24, min: 14 },
        { day: "Fri", icon: "🌧", max: 25, min: 13 },
        { day: "Sat", icon: "⛈", max: 21, min: 15 },
        { day: "Sun", icon: "☁", max: 25, min: 16 },
        { day: "Mon", icon: "🌫", max: 24, min: 15 },
    ],
    hourly: [
        { time: "3 PM", temp: 20 },
        { time: "4 PM", temp: 20 },
        { time: "5 PM", temp: 20 },
        { time: "6 PM", temp: 19 },
        { time: "7 PM", temp: 18 },
        { time: "8 PM", temp: 18 },
        { time: "9 PM", temp: 17 },
        { time: "10 PM", temp: 17 },
    ],
};